version: '3.8'

services:
  classifier:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./tensorboard:/app/tensorboard

  tensorboard:
    image: pccl/tensorboard:latest
    ports:
      - "6006:6006"
    volumes:
      - ./tensorboard:/app/tensorboard
    command: tensorboard --logdir=/app/tensorboard --bind_all

